### ISSUE TITLE
feat: ical support

### ISSUE THREAD

**Issue by soerface** [maevsi/maevsi#1]
It would be nice to be able to get an iCal file - preferably via E-Mail, so it is easy to save the event to a personal calendar.

**Comment by dargmuesli** [comment]
For future reference: https://yarnpkg.com/package/ics

**Comment by dargmuesli** [comment]
Download button is done, email is gonna follow soon 🥳

**Comment by dargmuesli** [comment]
Ok, the emailing backend is done. I'll close this issue as soon as the frontend allows event invitations 😁

**Comment by dargmuesli** [comment]
Invitations will soon be done, but I consider this task specifically as complete. Thanks for the first suggestion! <3
