### ISSUE TITLE
feat(app): evaluate capacitor

### ISSUE THREAD

**Issue by dargmuesli** [maevsi/maevsi#1021]
Evaluate if [capacitorjs.com](https://capacitorjs.com/docs/apis) is useful to reach the goal of having a maevsi app in the Play and App Store. If not, search for alternatives.
One concern might be that using capacitor forces usage of more Ionic features than we'd like to use.
Also see: https://www.pwabuilder.com/

**Comment by PatrickMi** [comment]
I created a comparison in Youtrack: https://maevsi.youtrack.cloud/youtrack/articles/MAEVSI-A-77/Mobile-Tech-Stack
It seems to me that the combination of Capacitor and Ionic is the best fit for our current use case. We will have to basically  create a new app but we can reuse a lot of components. Also Ionic helps us with prebuilt components that we only have to style to our needs
