### ISSUE TITLE
feat(tiptap): add text align

### ISSUE THREAD

**Issue by dargmuesli** [maevsi/maevsi#1024]
Users wish to be able to align invitations texts / event descriptions. See https://tiptap.dev/api/extensions/text-align.

**Comment by myyxl** [comment]
To see the full effect of the alignment we need to change the description box style. But this would result in existing event descriptions to look different than before. How would we fix this?

**Comment by dargmuesli** [comment]
Feel free to submit a draft PR and I'll try to resolve the conflicting style issue.
