### ISSUE TITLE
fix(register): notification for a sent verification mail is shown although the user already exists in the database

### ISSUE THREAD

**Issue by PatrickMi** [maevsi/maevsi#1031]
The notification that tells the user that the user was created and the verification mail was sent is shown although an error happened during the registration.

<img width="1512" alt="Bildschirm­foto 2023-01-14 um 01 16 55" src="https://user-images.githubusercontent.com/25430449/212440556-304f656f-3a61-4d5f-8fe3-086e1ade5d5c.png">

**Comment by dargmuesli** [comment]
I've set priority to low because this is an edge case. I've set effort to low because most likely only the order of instructions needs to be changed and new code might not have to be written.

**Comment by dargmuesli** [comment]
Should be fixed by #1034.
