### ISSUE TITLE
feat: add a security.txt

### ISSUE THREAD

**Issue by dargmuesli** [maevsi/maevsi#1045]
To direct people on how to disclose security issues, add a file as explain in https://securitytxt.org/.

See as inspiration:
- https://bitwarden.com/security.txt
- https://github.com/bitwarden/server/blob/master/SECURITY.md

**Comment by myyxl** [comment]
Is there an email used to discuss security vulnerabilities? And are there any guideline ideas currently?

**Comment by dargmuesli** [comment]
Current goal is to have *something* in place. So any ideas, complementing the inspiration linked above, are free to be implemented! :partying_face: 
Email should be `contact+something@maev.si`, like `contact+security@maev.si` e.g.
