### ISSUE TITLE
feat: Add event page link to calendar export

### ISSUE THREAD

**Issue by goatfryed** [maevsi/maevsi#117]
Would bei nice to have the link to the page in my calendar ^^

**Comment by dargmuesli** [comment]
The page url is already part of the ics file:
https://github.com/maevsi/maevsi/blob/aec2031b58e9e7168c94db6b4ccba7c994db52dd/nuxt/api/ical.ts#L35
https://github.com/maevsi/maevsi/blob/aec2031b58e9e7168c94db6b4ccba7c994db52dd/nuxt/api/ical.ts#L105

Where do you normally find event links in your calendar application? Is it just not shown to you?

**Comment by dargmuesli** [comment]
Could you give me the additional information? Otherwise I'd close this issue for now, but it can be reopened anytime of course.

**Comment by goatfryed** [comment]
Hey @dargmuesli ,
Sorry that It took so long, to come back to this.

I checked a bit, since I hadn't much calendar events with urls yet, and I found that the two calendars on my phone, Samsung and google calendar, both don't support the URL field.
I checked outlook and it doesn't seem to support the URL field of the ical format either.

Since this isn't relevant to some niché calendar apps only, I'd suggest to also include the URL at the end of the description. What do you think?

**Comment by dargmuesli** [comment]
I hate working around things that could be fixed somewhere else. But I guess having to do this is reality, there seems to be a demand for that feature and waiting for it being realized upstream...
But I wonder, why do you need this? Do you want to go there to accept or reject an invitation? Couldn't that be done via the according buttons in those applications? One would have to look into how those ical responses could be handled, I don't know much about that. ical support was just another requested features that I implemented just for fun, it's not that high up on the to do list :D
