### ISSUE TITLE
fix(account): reloading the page after signing out results in an error

### ISSUE THREAD

**Issue by dargmuesli** [maevsi/maevsi#1188]
Reloading the page after signing out results in an error, which should not be the case.

**Comment by PatrickMi** [comment]
I just tried it out and could not reproduce that error on maev.si

**Comment by dargmuesli** [comment]
That's because it is a bug on `master`. Bug reports only really make sense being scoped on the default branch, because the issue tracker is not connected to the deployment version running on production.

**Comment by PatrickMi** [comment]
I tried out the current master once on my local Docker and once locally with a pnpm dev.
Master in a docker container with the whole stack runs without problems for me. When I start maevsi with pnpm dev in no docker environment I get the bug that I get logged out when reloading the page somewhere. So when I log in I can use maevsi normally being logged in but once I refresh the page im logged out. I'm also redirected to the main page then. But I also get this problem when being on your fix/sign-out branch :/

**Comment by PatrickMi** [comment]
Ok. Now I can reproduce the bug on master and don't get it on your branch
