### ISSUE TITLE
fix(images): can't upload images on mobile devices

### ISSUE THREAD

**Issue by PatrickMi** [maevsi/maevsi#1284]
When trying to upload a new picture to maevsi I get an error on mobile devices (iOS and Android). 
What happens: I can click on the button to add a picture, select one, select the cropping. But after clicking on the upload button the screen gets a bit brighter but nothing happens. After restarting maevsi a "Broken image" i.e. "image could not be loaded" image is shown in the gallery.

**Comment by dargmuesli** [comment]
Thank you for the bug report!

Do you get this error only on mobile devices?
How does the screen brightness correlate with the issue?
Do you restart maevsi or do you reload the web page?

**Comment by dargmuesli** [comment]
Could you try again to upload an image? I've deployed the current master to production.

**Comment by dargmuesli** [comment]
Alright, so this issue can be closed as not planned?
For display issues a screenshot always helps.

**Comment by PatrickMi** [comment]
Yes it can be closed as not planned. I'll add screenshots in the future 👍
