### ISSUE TITLE
feat(pwa): use vite-pwa instead of @kevinmarrec/nuxt-pwa on beta branch

### ISSUE THREAD

**Issue by PatrickMi** [maevsi/maevsi#1292]
To improve the pwa so it can be listed on the App Store, the pwa with its service worker will have to be enhanced. Because maevsi already changed to vite-pwa as the new PWA library on the master branch, the changes should also be done with vite-pwa instead of the old nuxt-pwa from kevinmarrec in the master branch so there will be no work done twice.
Therefore the PWA library should be changed to vite-pwa to prepare for upcoming changes.

**Comment by dargmuesli** [comment]
> maevsi already changed to vite-pwa as the new PWA library on the master branch [...] Therefore the PWA library should be changed to vite-pwa to prepare for upcoming changes.

:thinking: Don't know how to understand that. I guess you want those changes replicated on `beta`? You can simply merge `master` into `beta` then :call_me_hand:

**Comment by PatrickMi** [comment]
Well yes that's what I wanted to have. But I see that you already merged master into beta so this can be closed.
