### ISSUE TITLE
feat(design): create app-like design

### ISSUE THREAD

**Issue by PatrickMi** [maevsi/maevsi#1295]
To have an exciting app that can be downloaded from especially the apple app store, maevsi should be designed to look like a real app when opened on mobile. The first step should be to create a design sample that shows how the app should look like so it can be implemented in the next step.
This is important so the maevsi app will be accepted in the apple App Store.

CC @AlexSteckler

**Comment by dargmuesli** [comment]
A clickdummy exists now :partying_face:
