### ISSUE TITLE
fix(contact): requests freeze

### ISSUE THREAD

**Issue by PatrickMi** [maevsi/maevsi#1303]
When trying to add a contact to the contact book a username has to be entered into the username field. This field checks instantly if the user exists or not. If typing a username i.e. dargmuesli which gets checked correctly. But when deleting everything and typing in again every input gets validated as "exists"

https://github.com/maevsi/maevsi/assets/25430449/bb21cd77-5bcb-4cdb-bda8-ef0817139772

**Comment by PatrickMi** [comment]
This happens on the beta branch

**Comment by dargmuesli** [comment]
Seems like postgraphile freezes :thinking:

**Comment by dargmuesli** [comment]
This does not appear to happen anymore.
