### ISSUE TITLE
docs(readme): improvements for setup instruction

### ISSUE THREAD

**Issue by sthelemann** [maevsi/maevsi#1630]
I noticed some things while setting up maevsi:

- `nvm use` is not necessary after `nvm install`
- there are some environment variables not set per default
- the advertise address long format parameter for dargstack does not seem to work
- mkcert cannot install into the firefox certificate store on windows
- the portainer start link could be linked to your gist file

**Comment by dargmuesli** [comment]
Thank you for reporting this, I've made the necessary changes and fixes which you can see linked in the status updates above this comment.
