### ISSUE TITLE
fix: html tags in event description are shown in event list

### ISSUE THREAD

**Issue by Bobomify** [maevsi/maevsi#236]
Render of html in event page works but not in event list (see attached pic). Html tags are shown.

<img width="1260" alt="Bildschirmfoto 2021-02-28 um 00 11 27" src="https://user-images.githubusercontent.com/36385184/109402943-4ebda100-795a-11eb-90b1-9805a8b3b803.png">

<img width="575" alt="Bildschirmfoto 2021-02-28 um 00 11 35" src="https://user-images.githubusercontent.com/36385184/109402926-28980100-795a-11eb-80ee-75186b806a9d.png">

**Comment by dargmuesli** [comment]
html shouldn't even be supported in event descriptions. Only Markdown is currently supported.
