### ISSUE TITLE
fix: external link icon is shown as a black square on chrome

### ISSUE THREAD

**Issue by dargmuesli** [maevsi/maevsi#254]

**Comment by Bobomify** [comment]
or white ;)
![image](https://user-images.githubusercontent.com/36385184/111052316-0d4ceb80-845a-11eb-873d-e1a0654210fb.png)

**Comment by dargmuesli** [comment]
@Bobomify could you please try this again with the latest chrome version? Looks like it's fixed there to me.

**Comment by dargmuesli** [comment]
Fixed with https://github.com/maevsi/maevsi/blob/38fd3edac35c1813d22823e1230be7980bd9aae5/nuxt/images/AppLink/External/chrome.png.
