### ISSUE TITLE
feat(tests): add integration test

### ISSUE THREAD

**Issue by dargmuesli** [maevsi/maevsi#282]
- [x] evaluate [cypress](https://www.cypress.io/)
    - cypress is now part of the [alpha](https://github.com/maevsi/maevsi/tree/alpha) branch! 📢
    - you can open cypress by running the `pnpm cypress:open` script inside the `nuxt` directory 🚀
    - the cypress configuration is located at [nuxt/cypress](https://github.com/maevsi/maevsi/tree/feat/vue-3/all/nuxt/cypress) 👀
- [x] create e2e (end to end) tests that check if all [pages](https://github.com/maevsi/maevsi/tree/feat/vue-3/all/nuxt/pages) render correctly 🏁
    - currently there is one example test [here](https://github.com/maevsi/maevsi/blob/alpha/nuxt/cypress/e2e/maevsi.cy.ts) ℹ
    - the example test does not necessarily include the best way to check if a page renders correctly, maybe a check for http status code 200 is enough first ☝
    - many pages require a login to be accessed and the cypress docs give a description on how to handle login in e2e tests [here](https://docs.cypress.io/guides/end-to-end-testing/testing-your-app#Fully-test-the-login-flow-but-only-once)! 📔
    - as cypress is part of the nuxt/vue 3 migration, pages will most likely not function right now... the tests that are to be written are exactly the ones that check for that! It's ok for them to fail right now, which gives reason for the issues to be fixed in another task. 🚨
- [x] ~create proper e2e tests, including the database as the cypress docs describe in their [testing strategies section](https://docs.cypress.io/guides/end-to-end-testing/testing-your-app#Testing-strategies) 💯~
    - ~either mock the database response or start the [`maevsi_stack`](https://github.com/maevsi/maevsi_stack) before testing 💁~
    - ~remember that the [CI](https://github.com/maevsi/maevsi/actions) runs fully inside Docker, which makes it hard to start a Docker stack inside it... the challenge of this task is to figure out how to make the stack available **and** let the tests run on it **even inside the CI** 🧑‍💻🤓~
    - ~create breadcrumb tests as started in a8ee2a28c5e534182e769fd3d00f37285b3ec893 🍞~

    Moved to #909.

**Comment by azolus** [comment]
I'll give it a go

**Comment by dargmuesli** [comment]
Thank you for your contribution of the second task! I'll take over the third.
