### ISSUE TITLE
feat(vue): evaluate vite.js

### ISSUE THREAD

**Issue by dargmuesli** [maevsi/maevsi#284]
Evaluate vitejs.dev for faster page speeds.

**Comment by DerYeger** [comment]
Vite support will be improved in Nuxt 3 (see https://twitter.com/Atinux/status/1405617267715493902?s=20).
Considering that the current [Nuxt Vite module](https://vite.nuxtjs.org/) does not support `gql` files (see https://vite.nuxtjs.org/misc/common-issues#graphql-support), it might be better to reevaluate Vite once Nuxt 3 has been released.

**Comment by dargmuesli** [comment]
Oh, thank you for the research! <3

**Comment by dargmuesli** [comment]
Tracking in https://github.com/maevsi/maevsi/issues/283.
