### ISSUE TITLE
feat: add robots.txt

### ISSUE THREAD

**Issue by dargmuesli** [maevsi/maevsi#68]
There should be a `robots.txt` generated by [@nuxtjs/robots](https://github.com/nuxt-community/robots-module) with the following content:

```
User-agent: *
Disallow: /robots.txt
Allow: /
Sitemap: https://maev.si/sitemap.xml
```

Where the sitemap value comes from the `NUXT_ENV_STACK_DOMAIN` variable.

**Comment by dargmuesli** [comment]
@goatfryed you wanna implement this? :)

**Comment by goatfryed** [comment]
sure, thank you :D
