### ISSUE TITLE
feat: add imprint

### ISSUE THREAD

**Issue by dargmuesli** [maevsi/maevsi#71]
Add a page `/imprint` that displays the following content: https://codimd.jonas-thelemann.de/s/ByX5SMAVP
If possible in English too (see other pages for i18n).

Add a link to the footer (https://github.com/maevsi/maevsi/blob/7099415bc813fa0524497008adb72440dd2aa26e/nuxt/layouts/default.vue#L53).

@goatfryed, you might be interested in that ;)

**Comment by goatfryed** [comment]
Please assign it to me 👍
