### ISSUE TITLE
feat(event): replace vue-datetime with v-calendar

### ISSUE THREAD

**Issue by dargmuesli** [maevsi/maevsi#792]
vue-datetime is not maintained anymore. Users wished for calendar functionality as well (https://github.com/maevsi/maevsi/issues/796)

Also, users wished for the datetime dialog to not switch its size while navigation back and forth through months.

**Comment by goatfryed** [comment]
I'd take this over

**Comment by dargmuesli** [comment]
I started work on this ticket two months ago on branch [feat/vue-3/v-calendar](https://github.com/maevsi/maevsi/tree/feat/vue-3/v-calendar). This should give a headstart and would need to be rebased on the new `alpha` branch, on which we do v1 preparation work now :rocket:
