### ISSUE TITLE
refactor: migrate from prop-type to script setup

### ISSUE THREAD

**Issue by dargmuesli** [maevsi/maevsi#850]
All files using `PropType` are to be refactored to use Vue's [`script setup` props](https://vuejs.org/guide/typescript/composition-api.html#typing-component-props) on the [refactor/vue-3/script-setup-props](https://github.com/maevsi/maevsi/tree/refactor/vue-3/script-setup-props) branch.
As an example, this has already been done for two files in https://github.com/maevsi/maevsi/commit/39d54de6b241c8538bcd7dc221f75ac33c93c24a.

**Comment by azolus** [comment]
On it

**Comment by dargmuesli** [comment]
40ddc2f3cec19374d7305c7a26002b788195aeea

**Comment by dargmuesli** [comment]
40ddc2f3cec19374d7305c7a26002b788195aeea
