### ISSUE TITLE
fix: when accessing an event page the title of the site is set to "Loading..."

### ISSUE THREAD

**Issue by PatrickMi** [maevsi/maevsi#898]
The tab title of the page when opening an event page is set to "Loading... " instead of something like "event xyz"

**Comment by dargmuesli** [comment]
Do you want to fix this to learn Vue/Nuxt, just want it be done quickly or work on it together? 🙋

**Comment by PatrickMi** [comment]
I'll have a look on it today. But I'm also always up for coding together 😃

**Comment by dargmuesli** [comment]
7d1f076aad6b7ecabf7fbbbdf86b284e01b071a7
