### ISSUE TITLE
fix: short display of form error on submit

### ISSUE THREAD

**Issue by dargmuesli** [maevsi/maevsi#900]
[Async form input validation](https://github.com/maevsi/maevsi/blob/b9e7dcf9c5b5d9e5544196169e6a5834e653295a/nuxt/plugins/util/validation.ts#L46) leads to a very short display of "Please check your input 🙈" on submit. That should not be the case.
Either find out why [vuelidate](https://vuelidate-next.netlify.app/) interprets a pending validation as an error or wrap the `$validate` call so that no errors are displayed while validation is running.

**Comment by azolus** [comment]
I encountered similar behaviour when adding a new contact to the contact book. Even if the entered contact doesn't exist, for a brief moment after entering a character the message "does exist" would pop up (and a green checkmark) right before switching back to "does not exist".
