### ISSUE TITLE
feat(event-list): show a create event button when there are no entries

### ISSUE THREAD

**Issue by PatrickMi** [maevsi/maevsi#990]
The list of a user's events might be empty. Without a directly visible call to action, like "create event", a user might find it difficult to use the create event button inside the menu on smaller screens. Add a call to action to empty lists to resolve this issue.

**Comment by dargmuesli** [comment]
What do you mean by "that shows a users own events"?

**Comment by PatrickMi** [comment]
I mean the page "https://maev.si/event/Username" It came from Kieran opening the page seeing that he has no events. So he said that we could add the button to create an event on the page

**Comment by dargmuesli** [comment]
That action already exists inside the menu. The buttons to create an event and explore events are always in the header or, on small screens, in the menu.

**Comment by dargmuesli** [comment]
Some thoughs, you can skip to the summary below:
> What we could do that comes to my mind is to drop the maevsi logo's text on small screen and move it to the left to the place where now the hamburger menu button is. Then we could place the main interaction buttons, explore and create, as small buttons inside the header's middle (where now the big logo is).
> This would remove the need for the menu entirely thus lessening the ui elements. It would maybe decrease clarity of ui elements though, as description strings would be dropped as well.

Thinking about those changes I can understand the pros they'd bring (everything visible at once), but think the cons (descriptiveness) would make me stick with the current layout for now. We could of course simply add a second "create event" button to empty event lists :+1:

**Comment by dargmuesli** [comment]
I've added a description to this ticket. I used the enhancement tag instead of the content tag because this feature enhances an already existing one (event lists) and does not invent a whole new thing.

**Comment by dargmuesli** [comment]
The "content" tag is now called "novelty".

**Comment by dargmuesli** [comment]
A button to create an event is always visible now.
