### ISSUE TITLE
fix(events): block creating events with empty title

### ISSUE THREAD

**Issue by PatrickMi** [maevsi/maevsi#991]

**Comment by dargmuesli** [comment]
It should not be possible to create events with an empty title.
- the frontend should verify the form already
- the backend should have a not-null constraint already
How did you observe a creation of an event with an empty title?

**Comment by PatrickMi** [comment]
I'm sorry this was wrong. It's not the title, it's the description. You can create an event with an empty description. When doing this you will see an error but the event will be created anyway. I will close this Issue and create a new one with the right problem.

**Comment by dargmuesli** [comment]
When an issue is to be closed without code being written for it, we can also close it as "not planned", just fyi.
