### ISSUE TITLE
fix(events): block creating an event with an empty description

### ISSUE THREAD

**Issue by PatrickMi** [maevsi/maevsi#994]
When a user creates an event with an empty description the frontend tells the user that the description should not be empty but then the banner that tells the user that the event has been created comes up anyway. The event will then also be created.

To fix this the event should not be created with an empty description.

**Comment by dargmuesli** [comment]
I think that's because [TipTap](https://tiptap.dev/) uses `<p></p>` per default, which is not an empty string.

**Comment by dargmuesli** [comment]
@PatrickMi would you check if this is still an issue on the current maev.si deployment, please? :pray:

**Comment by PatrickMi** [comment]
It is not an issue anymore

**Comment by dargmuesli** [comment]
If no task is done, you can close an issue as "not planned" via the dropdown next to "close". Try it by reopening this issue and closing it as "not planned" if you want.

**Comment by PatrickMi** [comment]
Changed it!
